name: swagger-sample

services:
  # 作成したAPI定義をブラウザで確認する
  swagger-ui:
    image: swaggerapi/swagger-ui:v5.18.2
    container_name: "swagger-ui"
    ports:
      - 8080:8080
    volumes:
      - ./swagger/openapi.yml:/usr/share/nginx/html/swagger/openapi.yml
      - ./swagger/paths:/usr/share/nginx/html/swagger/paths
    environment:
      - SWAGGER_JSON=/usr/share/nginx/html/swagger/openapi.yml
