openapi: "3.1.0"

info: 
  title: "Sample API"
  version: "1.0.0"
servers:
  - url: http://localhost:8080/{basePath}
    description: Local Server
    variables: 
      basePath:
        default: api
paths:
  /v1/hello:
    $ref: "./paths/hello.yml"